[project]
name = "src"
version = "0.1.0"
description = ""
authors = [
    {name = "Javier Cerón",email = "javier.ceron@utp.edu.co"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy (>=2.0)",
    "scipy (>=1.17,<1.18)",
    "pandas (>=3.0.5,<4.0.0)",
    "scikit-learn (>=1.9.0,<2.0.0)",
    "joblib (>=1.5.3,<2.0.0)",
    "mne (>=1.12.1,<2.0.0)",
    "matplotlib (>=3.11.1,<4.0.0)",
    "pyyaml (>=6.0.3,<7.0.0)",
    "tqdm (>=4.70.0,<5.0.0)" 
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "ruff (>=0.16.1,<0.17.0)",
    "pytest (>=9.1.1,<10.0.0)",
    "pytest-cov (>=7.1.0,<8.0.0)",
    "torchinfo (>=1.8.0,<2.0.0)"
]
